server:
 port: 9242

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vikas1235678/config-server
          clone-on-start: true 